# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: IRCC Tracker Check

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at noon (UTC)
  workflow_dispatch:      # Allow manual triggers

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/ms-playwright
          ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}-playwright
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest playwright
        playwright install chromium    # browser binary
        # playwright install-deps    # Linux dependencies
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run main.py (IRCC tracker App)
      run: python ./main.py
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        UCI: ${{ secrets.UCI }}
        IRCC_PASSWORD: ${{ secrets.IRCC_PASSWORD }}
