name: IRCC Tracker Check
on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at noon UTC (7:00 AM ET)
  workflow_dispatch:      # Allow manual triggers

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright python-dotenv
          playwright install chromium
          playwright install-deps  # Required for Linux

      - name: Run IRCC Tracker Script
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          UCI: ${{ secrets.UCI }}
          IRCC_PASSWORD: ${{ secrets.IRCC_PASSWORD }}
        run: python ./main.py  # Replace with your script name
